app = "arctic-ice-solutions"
primary_region = "iad"

[build]
  dockerfile = "deployment/production/Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[env]
  DATABASE_PATH = "/app/backend/data/yci_sqlite.db"



[[mounts]]
  source = "yci_data"
  destination = "/app/backend/data"
